tripfile: nets/ridepooling/Helsinki updated areas/area1/trips/area1_connected_sampled_0.3.trips.xml
percpass: 30
perctaxi: 10
capacity: 2
parkingfile: nets/ridepooling/Helsinki updated areas/area1/plain/area1_gcc_parkingareas_plain.add.xml
netfile: nets/ridepooling/Helsinki updated areas/area1/net/area1_connected.net.xml
sumoviewfile: simulation_test/sumoview.xml
run_gui_sim: False  # set to True to visualize the routes
run_cli_sim: False  # set to True to get taxi stats
