tripfile: nets/ridepooling/Helsinki updated areas/area1/area1_connected_sampled_0.2.trips.xml
percpass: 30
perctaxi: 15
capacity: 2
parkingfile: nets/ridepooling/Helsinki updated areas/area1/plain/area1_gcc_parkingareas_plain.add.xml
netfile: nets/ridepooling/Helsinki updated areas/area1/area1_connected.net.xml
sumoviewfile: simulation_test/sumoview.xml
run_gui_sim: True  # set to True to visualize the routes
run_cli_sim: True  # set to True to get taxi stats