train: True
test: True
test_baseline: False

env:
  timesteps: 3600
  total_iters: 200
  delta: 1  # step of policy applying (delta=1 means one simulation iteration)
  num_envs: 7  # change this to control parallelism
  sumo_seed: 4220
  sumocfg: "nets/ridepooling/Helsinki updated areas/area1/area1_sampled_0.2.sumocfg.xml"
  use_gui: False
  verbose: True
  taxi_reservations_logger:
    log_taxis: True
    log_reservations: True

baseline:
  num_periods: 3
  num_actions: 1

dqn:
  policy: MlpPolicy
  learning_rate: 0.01
  learning_starts: 1
  train_freq: 1
  gradient_steps: -1
  exploration_fraction: 0.1
  exploration_initial_eps: 0.05
  exploration_final_eps: 0.01
  verbose: 1

tests:
  num_tests: 1
