train: True
test: True
test_baseline: False

env:
  timesteps: 3000
  total_iters: 1000
  delta: 1
  num_envs: 2
  sumo_seed: 4220
  sumocfg: nets/ridepooling/area3_3000.sumocfg
  use_gui: False
  verbose: False

baseline:
  num_periods: 7
  num_actions: 1

dqn:
  policy: MlpPolicy
  learning_rate: 0.01
  learning_starts: 1
  train_freq: 1
  gradient_steps: -1
  exploration_fraction: 0.2
  exploration_initial_eps: 0.05
  exploration_final_eps: 0.01
  verbose: 1

tests:
  num_tests: 5
