tripfile: nets/ridepooling/Helsinki updated areas/area1/area1_connected_sampled_0.2.trips.xml
percpass: 50
perctaxi: 30
capacity: 2
parkingfile: nets/ridepooling/Helsinki updated areas/area1/area1_gcc_parkingareas_plain.add.xml